# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Pj17kZVDCpS0D1KwsymqrqCcf70J1N4
"""

# CI1---------------------
# Fuzzy sets
A = {'a':0.2, 'b':0.5, 'c':0.7}
B = {'a':0.6, 'b':0.4, 'c':0.8}
# Union
print("Union:")
for i in A:
  print(i, ":", max(A[i], B[i]))
# Intersection
print("\nIntersection:")
for i in A:
  print(i, ":", min(A[i], B[i]))
# Complement of A
print("\nComplement of A:")
for i in A:
  print(i, ":", 1 - A[i])
# Difference A-B
print("\nDifference A-B:")
for i in A:
  print(i, ":", min(A[i], 1 - B[i]))

# Cartesian Product (Fuzzy Relation)
print("\nCartesian Product:")
for i in A:
  for j in B:
    print((i,j), ":", min(A[i], B[j]))

# Max-Min Composition
R = [[0.2,0.7],
[0.6,0.3]]
S = [[0.5,0.4],
[0.8,0.9]]
print("\nMax-Min Composition:")
for i in range(2):
  for j in range(2):
    val = max(min(R[i][0],S[0][j]), min(R[i][1],S[1][j]))
    print(val, end=" ")
  print()


#CI2----------------------------------
import random
import warnings
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
# Ignore convergence warnings
warnings.filterwarnings("ignore")
# Load dataset
data = load_iris()
X = data.data
y = data.target
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)
POP_SIZE = 6
GENERATIONS = 5
# Create random individual [neurons, learning_rate, epochs]
def create_individual():
  return [
    random.randint(5, 50), # neurons
    random.uniform(0.001, 0.1), # learning rate
    random.randint(100, 300) # epochs
    ]
# Fitness function
def fitness(individual):
  neurons, lr, epochs = individual
  neurons = max(5, min(100, int(neurons)))
  lr = max(0.0001, float(lr)) # must be > 0
  epochs = max(50, int(epochs))
  model = MLPClassifier(
    hidden_layer_sizes=(neurons,),
    learning_rate_init=lr,
    max_iter=epochs,
    solver='adam'
    )
  model.fit(X_train, y_train)
  pred = model.predict(X_test)
  return accuracy_score(y_test, pred)
# Initialize population
population = [create_individual() for _ in range(POP_SIZE)]
for gen in range(GENERATIONS):
# Evaluate fitness


    scores = [(ind, fitness(ind)) for ind in population]
    scores.sort(key=lambda x: x[1], reverse=True)
    print(f"Generation {gen+1} Best Accuracy = {scores[0][1]:.4f}")
    # Select best 2
    best = [scores[0][0], scores[1][0]]
    # Crossover
    child = [
        random.choice([best[0][0], best[1][0]]),
        random.choice([best[0][1], best[1][1]]),
        random.choice([best[0][2], best[1][2]])
            ]
    # Mutation
    child[0] += random.randint(-5, 5)
    child[1] += random.uniform(-0.01, 0.01)
    child[2] += random.randint(-20, 20)
    child[0] = max(5, min(100, child[0]))
    child[1] = max(0.0001, child[1])
    child[2] = max(50, min(500, child[2]))
    # New population
    population = best + [child] + [create_individual() for _ in range(POP_SIZE -
best_solution = max(population, key=fitness)
print("\nBest Parameters Found:")
print("Neurons:", best_solution[0])
print("Learning Rate:", best_solution[1])
print("Epochs:", best_solution[2])
print("Final Accuracy:", fitness(best_solution))



#CI3-------------------------------------------------
import random
# Objective function (maximize)
def fitness(x):
  return -(x**2) + 10 # Maximum at x = 0
# Generate initial population
def init_population(size):
  return [random.uniform(-10, 10) for _ in range(size)]
# Clone antibodies
def clone(pop, clone_factor):
  clones = []
  for i, val in enumerate(pop):
    num_clones = int(clone_factor / (i + 1))
    clones += [val] * num_clones
  return clones
# Mutation
def mutate(clones):
  mutated = []
  for c in clones:
    mutation = random.uniform(-1, 1)
    mutated.append(c + mutation)
  return mutated
# Select best individuals
def select(pop, size):
  return sorted(pop, key=fitness, reverse=True)
# Clonal Selection Algorithm
def CSA(pop_size=10, generations=20):
  pop = init_population(pop_size)
  for gen in range(generations):
    pop = select(pop, pop_size)
    clones = clone(pop, clone_factor=10)
    mutated = mutate(clones)
    pop = select(mutated + pop, pop_size)
    best = max(pop, key=fitness)
    print(f"Generation {gen}: Best = {best}, Fitness = {fitness(best)}")
return best
# Run algorithm
best_solution = CSA()
print("Best Solution:", best_solution)




#CI4--------------------------------------------------------
import random
from deap import base, creator, tools, algorithms
# Define fitness (maximize function)
creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", list, fitness=creator.FitnessMax)
# Create toolbox
toolbox = base.Toolbox()
# Attribute generator (random float)
toolbox.register("attr_float", random.uniform, -10, 10)
# Structure initializers
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr
toolbox.register("population", tools.initRepeat, list, toolbox.individual)
# Fitness function
def eval_func(individual):
x = individual[0]
return (-(x**2) + 10,) # maximize
toolbox.register("evaluate", eval_func)
# Operators
toolbox.register("mate", tools.cxBlend, alpha=0.5)
toolbox.register("mutate", tools.mutGaussian, mu=0, sigma=1, indpb=0.2)
toolbox.register("select", tools.selTournament, tournsize=3)
# Main function
def main():
pop = toolbox.population(n=20)
# Run algorithm
algorithms.eaSimple(pop, toolbox,
cxpb=0.5,
mutpb=0.2,
ngen=20,
verbose=True)
best = tools.selBest(pop, 1)[0]
print("Best Individual:", best)
print("Fitness:", best.fitness.values)
if __name__ == "__main__":
main()
