# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Pj17kZVDCpS0D1KwsymqrqCcf70J1N4
"""

# CI1---------------------
# Fuzzy sets
A = {'a':0.2, 'b':0.5, 'c':0.7}
B = {'a':0.6, 'b':0.4, 'c':0.8}
# Union
print("Union:")
for i in A:
  print(i, ":", max(A[i], B[i]))
# Intersection
print("\nIntersection:")
for i in A:
  print(i, ":", min(A[i], B[i]))
# Complement of A
print("\nComplement of A:")
for i in A:
  print(i, ":", 1 - A[i])
# Difference A-B
print("\nDifference A-B:")
for i in A:
  print(i, ":", min(A[i], 1 - B[i]))

# Cartesian Product (Fuzzy Relation)
print("\nCartesian Product:")
for i in A:
  for j in B:
    print((i,j), ":", min(A[i], B[j]))

# Max-Min Composition
R = [[0.2,0.7],
[0.6,0.3]]
S = [[0.5,0.4],
[0.8,0.9]]
print("\nMax-Min Composition:")
for i in range(2):
  for j in range(2):
    val = max(min(R[i][0],S[0][j]), min(R[i][1],S[1][j]))
    print(val, end=" ")
  print()


#CI2----------------------------------
import random
import warnings
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
# Ignore convergence warnings
warnings.filterwarnings("ignore")
# Load dataset
data = load_iris()
X = data.data
y = data.target
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)
POP_SIZE = 6
GENERATIONS = 5
# Create random individual [neurons, learning_rate, epochs]
def create_individual():
  return [
    random.randint(5, 50), # neurons
    random.uniform(0.001, 0.1), # learning rate
    random.randint(100, 300) # epochs
    ]
# Fitness function
def fitness(individual):
  neurons, lr, epochs = individual
  neurons = max(5, min(100, int(neurons)))
  lr = max(0.0001, float(lr)) # must be > 0
  epochs = max(50, int(epochs))
  model = MLPClassifier(
    hidden_layer_sizes=(neurons,),
    learning_rate_init=lr,
    max_iter=epochs,
    solver='adam'
    )
  model.fit(X_train, y_train)
  pred = model.predict(X_test)
  return accuracy_score(y_test, pred)
# Initialize population
population = [create_individual() for _ in range(POP_SIZE)]
for gen in range(GENERATIONS):
# Evaluate fitness


    scores = [(ind, fitness(ind)) for ind in population]
    scores.sort(key=lambda x: x[1], reverse=True)
    print(f"Generation {gen+1} Best Accuracy = {scores[0][1]:.4f}")
    # Select best 2
    best = [scores[0][0], scores[1][0]]
    # Crossover
    child = [
        random.choice([best[0][0], best[1][0]]),
        random.choice([best[0][1], best[1][1]]),
        random.choice([best[0][2], best[1][2]])
            ]
    # Mutation
    child[0] += random.randint(-5, 5)
    child[1] += random.uniform(-0.01, 0.01)
    child[2] += random.randint(-20, 20)
    child[0] = max(5, min(100, child[0]))
    child[1] = max(0.0001, child[1])
    child[2] = max(50, min(500, child[2]))
    # New population
    population = best + [child] + [create_individual() for _ in range(POP_SIZE -
best_solution = max(population, key=fitness)
print("\nBest Parameters Found:")
print("Neurons:", best_solution[0])
print("Learning Rate:", best_solution[1])
print("Epochs:", best_solution[2])
print("Final Accuracy:", fitness(best_solution))



#CI3-------------------------------------------------
import random
# Objective function (maximize)
def fitness(x):
  return -(x**2) + 10 # Maximum at x = 0
# Generate initial population
def init_population(size):
  return [random.uniform(-10, 10) for _ in range(size)]
# Clone antibodies
def clone(pop, clone_factor):
  clones = []
  for i, val in enumerate(pop):
    num_clones = int(clone_factor / (i + 1))
    clones += [val] * num_clones
  return clones
# Mutation
def mutate(clones):
  mutated = []
  for c in clones:
    mutation = random.uniform(-1, 1)
    mutated.append(c + mutation)
  return mutated
# Select best individuals
def select(pop, size):
  return sorted(pop, key=fitness, reverse=True)
# Clonal Selection Algorithm
def CSA(pop_size=10, generations=20):
  pop = init_population(pop_size)
  for gen in range(generations):
    pop = select(pop, pop_size)
    clones = clone(pop, clone_factor=10)
    mutated = mutate(clones)
    pop = select(mutated + pop, pop_size)
    best = max(pop, key=fitness)
    print(f"Generation {gen}: Best = {best}, Fitness = {fitness(best)}")
return best
# Run algorithm
best_solution = CSA()
print("Best Solution:", best_solution)




#CI4--------------------------------------------------------
import random
from deap import base, creator, tools, algorithms
# Define fitness (maximize function)
creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", list, fitness=creator.FitnessMax)
# Create toolbox
toolbox = base.Toolbox()
# Attribute generator (random float)
toolbox.register("attr_float", random.uniform, -10, 10)
# Structure initializers
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr
toolbox.register("population", tools.initRepeat, list, toolbox.individual)
# Fitness function
def eval_func(individual):
x = individual[0]
return (-(x**2) + 10,) # maximize
toolbox.register("evaluate", eval_func)
# Operators
toolbox.register("mate", tools.cxBlend, alpha=0.5)
toolbox.register("mutate", tools.mutGaussian, mu=0, sigma=1, indpb=0.2)
toolbox.register("select", tools.selTournament, tournsize=3)
# Main function
def main():
pop = toolbox.population(n=20)
# Run algorithm
algorithms.eaSimple(pop, toolbox,
cxpb=0.5,
mutpb=0.2,
ngen=20,
verbose=True)
best = tools.selBest(pop, 1)[0]
print("Best Individual:", best)
print("Fitness:", best.fitness.values)
if __name__ == "__main__":
main()

#CI5-------------------------------------------------------------

import numpy as np
import random
# Distance matrix
# Let there are 5 cities (A,B,C,D,E)
dist = np.array([
    [0, 2, 2, 5, 7],
    [2, 0, 4, 8, 2],
    [2, 4, 0, 1, 3],
    [5, 8, 1, 0, 2],
    [7, 2, 3, 2, 0]
])
# No. of cities
n = len(dist)
# Initialize pheromone matrix
pheromone = np.ones((n, n))
# Parameters
alpha = 1  # phermon importance
beta = 1  # distance importance
evaporation = 0.5  
Q = 100  # amount of pheromone deposited
# Calculates total route distance
def route_length(route):
    return sum(
        dist[route[i]][route[i+1]]
        for i in range(len(route)-1)
    ) + dist[route[-1]][route[0]]
# Choose next city
def choose_next(city, visited):
    probs = []
    for j in range(n):
        if j not in visited:
            # Pheromone value
            tau = pheromone[city][j]**alpha

            # Heuristic Value
            if dist[city][j] != 0:
                eta = (1 / dist[city][j])**beta
            else:
                eta = 0

            probs.append((j, tau*eta))

    # Ignores first value
    total = sum(p for _, p in probs)

    r = random.random()
    s = 0

    for j,p in probs:
        s += p/total
        if r <= s:
            return j
# Ant Colony Optimization function
def aco(iterations=50, ants=10):
    best_route = None
    best_length = float('inf')

    for _ in range(iterations):
        all_routes = []
        for _ in range(ants):
            route = [random.randint(0, n-1)]

            while len(route) < n:
                next_city = choose_next(route[-1], route)
                route.append(next_city)

            all_routes.append(route)

            length = route_length(route)
            
            if length < best_length:
                best_length = length
                best_route = route

        # Evaporation
        pheromone[:] *= (1-evaporation)

        # Pheromone update
        for route in all_routes:
            lenght = route_length(route)

            for i in range(n-1):
                pheromone[route[i]][route[i+1]] += Q/length

    return best_route, best_length
route, length = aco()
print("Best route:", route)
print("Shortest distance:", length)
#___________________________________________
#DC3---------------------------------------------------------
import random
# Simulated servers
servers = [
{"name": "Server-1", "connections": 0},
{"name": "Server-2", "connections": 0},
{"name": "Server-3", "connections": 0}
]
# Round Robin Load Balancing
def round_robin(requests):
    print("\nRound Robin Allocation:")
    n = len(servers)
    for i, req in enumerate(requests):
        server = servers[i % n]
        server["connections"] += 1
        print(f"Request {req} → {server['name']}")
# Random Load Balancing
def random_lb(requests):
    print("\nRandom Allocation:")
    for req in requests:
        server = random.choice(servers)
        server["connections"] += 1
        print(f"Request {req} → {server['name']}")
# Least Connections
def least_connections(requests):
    print("\nLeast Connections Allocation:")
    for req in requests:
        server = min(servers, key=lambda s: s["connections"])
        server["connections"] += 1
        print(f"Request {req} → {server['name']}")
# Reset server connections
def reset_servers():
for s in servers:
    s["connections"] = 0
# Simulated client requests
requests = [f"Req-{i}" for i in range(1, 11)]
# Run simulations
round_robin(requests)
reset_servers()
random_lb(requests)
reset_servers()
least_connections(requests)



#DC5--------------------------------------------------------
data = [
("2001", 30), ("2001", 32),
("2002", 25), ("2002", 28),
("2003", 35), ("2003", 36),
("2004", 20), ("2004", 22)
]
def mapper(data):
    return [(year, temp) for year, temp in data]
from collections import defaultdict
def shuffle(mapped):
    d = defaultdict(list)
    for year, temp in mapped:
        d[year].append(temp)
    return d
def reducer(shuffled):
    avg_temp = {}
    for year, temps in shuffled.items():
        avg_temp[year] = sum(temps) / len(temps)
    return avg_temp
mapped = mapper(data)
shuffled = shuffle(mapped)
reduced = reducer(shuffled)
hottest = max(reduced, key=reduced.get)
coolest = min(reduced, key=reduced.get)
print("Average:", reduced)
print("Hottest Year:", hottest)
print("Coolest Year:", coolest)
